[package]
name = "diamond"
version = "0.1.0"
edition = "2021"

[dependencies]

[lib]
name = "diamond_core"
path = "src/lib.rs"

[[bin]]
name = "repl"
path = "src/bin/repl.rs"

[[bin]]
name = "interpreter"
path = "src/bin/interpreter.rs"
